version: '3'
services:
  jupyterlab:
    build: .
    container_name: 'jupyterlab'
    working_dir: '/root/src'
    tty: true
    volumes:
      - ${SRC_PATH}:/root/src
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost